### ISSUE TITLE
Bug: The value `(sqrt-r 2)` is not of type REAL

### ISSUE THREAD

**Issue by pqnelson** [stylewarning/computable-reals#1]
I have loaded computable-reals using quicklisp into my slime repl, and when I try:

```
USER> (sqrt-r 2)
+1.41421356237309504880...
USER> (< (sqrt-r 2) 2)
```

Slime raises the issue:

```
The value
  +1.41421356237309504880...
is not of type
  REAL
when binding SB-KERNEL::N1
   [Condition of type TYPE-ERROR]
```

When I query directly if the squareroot of 2 is a real or not:

```
USER> (realp (sqrt-r 2))
nil
USER> 
```

I'm running this on SBCL 1.4.16.debian.

**Comment by stylewarning** [comment]
I'm *terribly* sorry for missing this bug report. I didn't properly setup GitHub to alert me!

This is not a bug, but maybe somewhat surprising behavior. This library doesn't integrate into Common Lisp's functions like `realp` and `<`. Common Lisp, unfortunately, doesn't provide a way to extend the numerical system sensibly.

The correct way to check if something is a real value under the computable reals is to use `CREAL-P`:

```
> (cr:creal-p 2)
T
> (cr:creal-p (sqrt-r 2))
T
```

Currently there is no exported comparison function that's useful. The problem with comparison is that *exact* comparison might be non-terminating. This might sound ridiculous, but
```
(cr:fabled-equality-function (cr:sqrt-r 2) (cr:sqrt-r 2))
```
would never terminate because it would need to compare an infinite number of digits!

So the best we can do is compare against a rational approximation of the number. So you can do:

```
> (< (cr:rational-approx-r (sqrt-r 2) 100) 2)
T
```

which says that the square root of 2 is less than 2 at least to a precision of `1/2^100`.
